"""Generate the normal-pool coverage inventory from shared mappings."""
from pathlib import Path
import json
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from dependencies import RULE_AXES

rows = json.loads((ROOT / 'normal_catalogue.json').read_text(encoding='utf-8'))
mapping = json.loads((ROOT / 'modifier_rules.json').read_text(encoding='utf-8'))
policy = set(json.loads((ROOT / 'normal_free_policy.json').read_text(encoding='utf-8')))
lines = ['# Normal-map dependency audit', '',
    'Generated by `scripts/audit_normal_catalogue.py`. Every current normal catalogue entry is accounted for. Coverage means a rule or an explicit policy exists; it does not mean every build interaction has been simulated.', '',
    '| Modifier | Assessment path | Dependencies checked |', '| --- | --- | --- |']
unknown = []
for row in rows:
    rule = mapping.get(row['id'])
    status = rule or ('User Free policy' if row['id'] in policy else 'UNASSESSED')
    if status == 'UNASSESSED':
        unknown.append(row['id'])
    lines.append('| ' + row['text'].replace('|', ' · ') + ' | ' + status + ' | ' + ', '.join(RULE_AXES.get(rule, [])) + ' |')
lines += ['', f'{len(rows)} entries; {sum(r["id"] in policy for r in rows)} retain the user Free policy; {len(unknown)} have no assessment path.', '',
    'Priority gaps: actual aura/curse contribution, special ailment requirements, item-trigger details, remote-entity durability, conditional flask/charge uptime, selected-skill ambiguity, and encounter-specific survival thresholds. Skill recognition does not by itself resolve these gaps.']
(ROOT / 'docs').mkdir(exist_ok=True)
(ROOT / 'docs/normal-modifier-audit.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f'Audited {len(rows)} normal entries; {len(unknown)} without a rule or explicit policy.')
